const products = [
  {
    id: 1,
    name: "Havit HV-G92 Gamepad",
    price: 192.0,
    rating: 4.5,
    reviews: 88,
    image: "/images/products/1.jpg",
    isNew: true,
    category: "Gaming",
  },
  {
    id: 2,
    name: "AK-900 Wired Keyboard",
    price: 960.0,
    rating: 4.0,
    reviews: 75,
    image: "/images/products/2.jpg",
    isNew: false,
    category: "Electronics",
  },
  {
    id: 3,
    name: "IPS LCD Gaming Monitor",
    price: 370.0,
    rating: 4.8,
    reviews: 99,
    image: "/images/products/3.jpg",
    isNew: true,
    category: "Electronics",
  },
  {
    id: 4,
    name: "RGB Liquid CPU Cooler",
    price: 160.0,
    rating: 4.4,
    reviews: 65,
    image: "/images/products/4.jpg",
    isNew: false,
    category: "Electronics",
  },
  {
    id: 5,
    name: "Logitech G502 Mouse",
    price: 87.0,
    rating: 4.7,
    reviews: 130,
    image: "/images/products/5.jpg",
    isNew: true,
    category: "Gaming",
  },
  {
    id: 6,
    name: "Razer Kraken Headset",
    price: 112.0,
    rating: 4.3,
    reviews: 55,
    image: "/images/products/6.jpg",
    isNew: false,
    category: "Gaming",
  },
];
